import { motion } from 'motion/react';
import { ArrowRight, Droplets, Leaf, Mail, MapPin, Phone, ShieldCheck, Sparkles, Sprout } from 'lucide-react';
import { ProductRangeSection } from './ProductRangeSection';

interface LandingPageProps { onGetStarted: () => void }

const reveal = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-70px' }, transition: { duration: 0.55, ease: 'easeOut' as const } };
const benefits = [
  { Icon: Droplets, title: 'Nourishes', detail: 'For skin' },
  { Icon: Sparkles, title: 'Conditions', detail: 'For hair' },
  { Icon: Leaf, title: 'Plant based', detail: 'Single oil' },
];

export function LandingPage({ onGetStarted }: LandingPageProps) {
  return <div className="min-h-screen overflow-hidden bg-canvas text-ink">
    <header className="absolute inset-x-0 top-0 z-20 border-b border-white/20 bg-ink/20 text-white backdrop-blur-md">
      <div className="mx-auto flex min-h-18 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="flex items-center gap-3 font-display text-xl font-semibold"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/15"><Leaf className="h-5 w-5" /></span><span>Akudha Enterprises</span></a><nav className="flex items-center gap-3"><a href="#range" className="hidden min-h-11 items-center px-3 text-sm font-semibold sm:flex">Products</a><a href="#origin" className="hidden min-h-11 items-center px-3 text-sm font-semibold md:flex">Our origin</a><a href="#contact" className="hidden min-h-11 items-center px-3 text-sm font-semibold md:flex">Contact</a><button type="button" onClick={onGetStarted} className="min-h-11 rounded-control border border-white/40 px-4 text-sm font-semibold hover:bg-white hover:text-ink">Staff sign in</button></nav></div>
    </header>

    <main id="top">
      <section className="relative min-h-[760px] bg-ink text-white"><img src="/images/baobab-oil-hero.webp" alt="Featured Akudha Baobab Oil bottle in a Zimbabwean landscape" className="absolute inset-0 h-full w-full object-cover object-[65%_center]" fetchPriority="high" /><div className="absolute inset-0 bg-gradient-to-r from-[#18241d]/98 via-[#18241d]/78 to-[#18241d]/10" /><div className="relative mx-auto flex min-h-[760px] max-w-7xl items-center px-5 pt-24 sm:px-8"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }} className="max-w-2xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em]"><Sparkles className="h-4 w-4 text-[#e6b56e]" /> African botanical oils &amp; butters</p><h1 className="font-display text-5xl font-semibold leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">Botanical care,<br /><span className="text-[#efc98f]">rooted in Africa.</span></h1><p className="mt-6 max-w-md text-lg leading-8 text-white/82">Akudha creates a growing range of plant oils and butters for skin and hair, celebrating Baobab, Kalahari Melon, Mongongo and Mafura.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#range" className="inline-flex min-h-12 items-center gap-2 rounded-control bg-[#efc98f] px-6 font-bold text-ink hover:bg-white">Explore the range <ArrowRight className="h-4 w-4" /></a><a href="#contact" className="inline-flex min-h-12 items-center rounded-control border border-white/35 px-6 font-semibold text-white hover:bg-white/10">Contact Akudha</a></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-3 border-t border-white/20 pt-5 text-sm"><span><strong className="block text-lg">4 botanicals</strong>distinct products</span><span><strong className="block text-lg">Oils &amp; butter</strong>skin and hair care</span><span><strong className="block text-lg">Zimbabwe</strong>home of Akudha</span></div></motion.div></div></section>

      <ProductRangeSection />

      <section id="product" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><motion.div {...reveal} className="relative"><img src="/images/baobab-oil-ritual.webp" alt="Akudha Baobab Oil dispensed into a hand" loading="lazy" className="aspect-[4/3] w-full rounded-feature object-cover shadow-frost" /><div className="absolute -bottom-5 right-5 rounded-surface border border-line bg-surface p-4 shadow-frost"><span className="block text-xs font-bold uppercase tracking-wider text-brand-strong">Baobab label specification</span><strong className="mt-1 block font-display text-xl">14 cm × 5.5 cm label</strong></div></motion.div><motion.div {...reveal}><p className="text-sm font-bold uppercase tracking-[.16em] text-brand-strong">Featured botanical</p><h2 className="mt-3 font-display text-4xl font-semibold leading-tight sm:text-5xl">Baobab oil.<br />A simple daily ritual.</h2><p className="mt-6 text-lg leading-8 text-ink-muted">Akudha Baobab Oil contains <em>Adansonia digitata</em> seed oil. Apply a few drops to clean skin or hair and massage gently until absorbed.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{benefits.map(({ Icon, title, detail }) => <div key={title} className="rounded-surface border border-line bg-surface p-4"><Icon className="h-5 w-5 text-brand-strong" /><strong className="mt-4 block">{title}</strong><span className="text-sm text-ink-muted">{detail}</span></div>)}</div><div className="mt-8 rounded-surface bg-ink p-5 text-white"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-[#efc98f]" /><div><strong>Clear label information</strong><p className="mt-1 text-sm leading-6 text-white/70">Directions, storage guidance, batch, manufacturing and expiry fields are built into the production label.</p></div></div></div></motion.div></div></section>

      <section id="origin" className="bg-ink px-5 py-20 text-white sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><motion.div {...reveal}><p className="text-sm font-bold uppercase tracking-[.16em] text-[#efc98f]">Botanical origin</p><h2 className="mt-3 font-display text-4xl font-semibold leading-tight sm:text-5xl">African botanicals. Zimbabwean enterprise.</h2><p className="mt-6 text-lg leading-8 text-white/72">Baobab, Kalahari melon, mongongo and mafura each bring a distinct botanical identity to the Akudha range. The operations system records sourcing, quality and ethical payouts from intake through production.</p><div className="mt-9 grid gap-5 sm:grid-cols-2"><div className="border-l-2 border-[#efc98f] pl-4"><Sprout className="h-5 w-5 text-[#efc98f]" /><strong className="mt-3 block">Responsible sourcing</strong><p className="mt-1 text-sm leading-6 text-white/65">Harvest records capture origin, grade, weight and payout.</p></div><div className="border-l-2 border-[#efc98f] pl-4"><ShieldCheck className="h-5 w-5 text-[#efc98f]" /><strong className="mt-3 block">Operational proof</strong><p className="mt-1 text-sm leading-6 text-white/65">Batches and labels are tracked from intake through production.</p></div></div></motion.div><motion.img {...reveal} src="/images/baobab-origin.webp" alt="Baobab processing in a Zimbabwean dryland landscape" loading="lazy" className="aspect-[3/2] w-full rounded-feature object-cover shadow-2xl" /></div></section>

      <section className="px-5 py-20 sm:px-8 sm:py-28"><motion.div {...reveal} className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.16em] text-brand-strong">Made to be accountable</p><h2 className="mt-3 font-display text-4xl font-semibold sm:text-5xl">Product information you can verify.</h2><p className="mt-5 text-lg leading-8 text-ink-muted">Every Akudha label leaves space for the details that matter after production.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[['01','Batch identity','A clear lot reference connects finished stock to its production record.'],['02','Dates and storage','Manufacturing, expiry and storage guidance remain visible on pack.'],['03','Scannable barcode','Barcodes are generated from the saved product record and audited before production printing.']].map(([number,title,copy]) => <article key={number} className="rounded-feature border border-line bg-surface p-6"><span className="font-mono text-sm font-bold text-brand">{number}</span><h3 className="mt-8 font-display text-2xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-ink-muted">{copy}</p></article>)}</div></motion.div></section>

      <section id="contact" className="bg-brand-soft px-5 py-20 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr]"><motion.div {...reveal}><p className="text-sm font-bold uppercase tracking-[.16em] text-brand-strong">Talk to Akudha</p><h2 className="mt-3 font-display text-4xl font-semibold sm:text-5xl">Wholesale, product and partnership enquiries.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-ink-muted">Reach Akudha Enterprises directly for product availability, distribution and sourcing partnerships.</p></motion.div><motion.div {...reveal} className="grid gap-3"><a href="tel:+263773662537" className="flex min-h-16 items-center gap-4 rounded-surface border border-line bg-surface px-5 hover:border-brand"><Phone className="h-5 w-5 text-brand-strong" /><span><small className="block text-xs font-bold uppercase tracking-wider text-ink-muted">Phone</small><strong>+263 77 366 2537</strong></span></a><a href="mailto:akudhaenterprises@gmail.com" className="flex min-h-16 items-center gap-4 rounded-surface border border-line bg-surface px-5 hover:border-brand"><Mail className="h-5 w-5 text-brand-strong" /><span><small className="block text-xs font-bold uppercase tracking-wider text-ink-muted">Email</small><strong>akudhaenterprises@gmail.com</strong></span></a><div className="flex min-h-16 items-center gap-4 rounded-surface border border-line bg-surface px-5"><MapPin className="h-5 w-5 text-brand-strong" /><span><small className="block text-xs font-bold uppercase tracking-wider text-ink-muted">Location</small><strong>Stand 250, Dotito Township, Mt Darwin, Zimbabwe</strong></span></div></motion.div></div></section>
    </main>

    <footer className="bg-ink px-5 py-8 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm sm:flex-row sm:items-center sm:justify-between"><span className="font-display text-lg font-semibold">Akudha Enterprises Zimbabwe (Pvt) Ltd</span><span className="text-white/55">African botanical oils &amp; butters · Nature’s best, naturally.</span><button type="button" onClick={onGetStarted} className="min-h-11 self-start rounded-control border border-white/25 px-4 font-semibold sm:self-auto">Staff sign in</button></div></footer>
  </div>;
}
